FROM postgres:17-alpine3.21

# Copy initialization script
COPY ./scripts/init-db.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD ["pg_isready", "-U", "postgres"]

EXPOSE 5432